-- MySQL Script generated by MySQL Workbench
-- Fri Feb 14 13:02:52 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema escuela
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema escuela
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `escuela` DEFAULT CHARACTER SET utf8 ;
USE `escuela` ;

-- -----------------------------------------------------
-- Table `escuela`.`Alumno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `escuela`.`Alumno` (
  `id_alumno` INT NOT NULL,
  `nombre_alumno` VARCHAR(45) NULL,
  `apellido1_alumno` VARCHAR(45) NULL,
  `apellido2_alumno` VARCHAR(45) NULL,
  PRIMARY KEY (`id_alumno`),
  UNIQUE INDEX `dni_alumno_UNIQUE` (`id_alumno` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `escuela`.`Asignatura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `escuela`.`Asignatura` (
  `id_asignatura` INT NOT NULL,
  `nombre_asignatura` VARCHAR(45) NULL,
  `curso` VARCHAR(45) NULL,
  `horas_semana` DECIMAL(2,2) NULL,
  PRIMARY KEY (`id_asignatura`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `escuela`.`Grupo_asignatura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `escuela`.`Grupo_asignatura` (
  `id_grupo_asignatura` INT NOT NULL,
  `nombre_grupo_asignatura` VARCHAR(45) NULL,
  `curso` VARCHAR(45) NOT NULL,
  `letra` VARCHAR(45) NOT NULL,
  `Asignatura_id_asignatura` INT NULL,
  PRIMARY KEY (`id_grupo_asignatura`, `Asignatura_id_asignatura`),
  UNIQUE INDEX `id_grupo_asignatura_UNIQUE` (`id_grupo_asignatura` ASC) VISIBLE,
  INDEX `fk_Grupo_asignatura_Asignatura1_idx` (`Asignatura_id_asignatura` ASC) VISIBLE,
  CONSTRAINT `fk_Grupo_asignatura_Asignatura1`
    FOREIGN KEY (`Asignatura_id_asignatura`)
    REFERENCES `escuela`.`Asignatura` (`id_asignatura`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `escuela`.`Profesor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `escuela`.`Profesor` (
  `dni_profesor` INT NOT NULL,
  `nombre_profesor` VARCHAR(45) NULL,
  `apellido1_profesor` VARCHAR(45) NULL,
  `apellido2_profesor` VARCHAR(45) NULL,
  PRIMARY KEY (`dni_profesor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `escuela`.`Departamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `escuela`.`Departamento` (
  `id_departamento` INT NOT NULL,
  `nombre_departamento` VARCHAR(45) NULL,
  `telefono_departamento` VARCHAR(45) NULL,
  `email_departamento` VARCHAR(45) NULL,
  PRIMARY KEY (`id_departamento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `escuela`.`Aula`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `escuela`.`Aula` (
  `id_aula` INT NOT NULL AUTO_INCREMENT,
  `capacidad_aula` INT NOT NULL,
  `ubicacion_aula` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_aula`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `escuela`.`Grupo_asignatura_has_Profesor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `escuela`.`Grupo_asignatura_has_Profesor` (
  `Grupo_asignatura_id_grupo_asignatura` INT NOT NULL,
  `Profesor_dni_profesor` INT NOT NULL,
  PRIMARY KEY (`Grupo_asignatura_id_grupo_asignatura`, `Profesor_dni_profesor`),
  INDEX `fk_Grupo_asignatura_has_Profesor_Profesor1_idx` (`Profesor_dni_profesor` ASC) VISIBLE,
  INDEX `fk_Grupo_asignatura_has_Profesor_Grupo_asignatura1_idx` (`Grupo_asignatura_id_grupo_asignatura` ASC) VISIBLE,
  CONSTRAINT `fk_Grupo_asignatura_has_Profesor_Grupo_asignatura1`
    FOREIGN KEY (`Grupo_asignatura_id_grupo_asignatura`)
    REFERENCES `escuela`.`Grupo_asignatura` (`id_grupo_asignatura`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Grupo_asignatura_has_Profesor_Profesor1`
    FOREIGN KEY (`Profesor_dni_profesor`)
    REFERENCES `escuela`.`Profesor` (`dni_profesor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `escuela`.`Alumno_has_Grupo_asignatura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `escuela`.`Alumno_has_Grupo_asignatura` (
  `Alumno_id_alumno` INT NOT NULL,
  `Grupo_asignatura_id_grupo_asignatura` INT NOT NULL,
  `fecha_matriculacion` DATE NOT NULL,
  `calificacion` DECIMAL(2,2) NULL,
  PRIMARY KEY (`Alumno_id_alumno`, `Grupo_asignatura_id_grupo_asignatura`),
  INDEX `fk_Alumno_has_Grupo_asignatura_Grupo_asignatura1_idx` (`Grupo_asignatura_id_grupo_asignatura` ASC) VISIBLE,
  INDEX `fk_Alumno_has_Grupo_asignatura_Alumno1_idx` (`Alumno_id_alumno` ASC) VISIBLE,
  CONSTRAINT `fk_Alumno_has_Grupo_asignatura_Alumno1`
    FOREIGN KEY (`Alumno_id_alumno`)
    REFERENCES `escuela`.`Alumno` (`id_alumno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Alumno_has_Grupo_asignatura_Grupo_asignatura1`
    FOREIGN KEY (`Grupo_asignatura_id_grupo_asignatura`)
    REFERENCES `escuela`.`Grupo_asignatura` (`id_grupo_asignatura`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `escuela`.`Aula_has_Grupo_asignatura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `escuela`.`Aula_has_Grupo_asignatura` (
  `Aula_id_aula` INT NOT NULL,
  `Grupo_asignatura_id_grupo_asignatura` INT NOT NULL,
  PRIMARY KEY (`Aula_id_aula`, `Grupo_asignatura_id_grupo_asignatura`),
  INDEX `fk_Aula_has_Grupo_asignatura_Grupo_asignatura1_idx` (`Grupo_asignatura_id_grupo_asignatura` ASC) VISIBLE,
  INDEX `fk_Aula_has_Grupo_asignatura_Aula1_idx` (`Aula_id_aula` ASC) VISIBLE,
  CONSTRAINT `fk_Aula_has_Grupo_asignatura_Aula1`
    FOREIGN KEY (`Aula_id_aula`)
    REFERENCES `escuela`.`Aula` (`id_aula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Aula_has_Grupo_asignatura_Grupo_asignatura1`
    FOREIGN KEY (`Grupo_asignatura_id_grupo_asignatura`)
    REFERENCES `escuela`.`Grupo_asignatura` (`id_grupo_asignatura`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
