SELECT CITY.NAME AS CITY, COUNTRY.NAME AS COUNTRY 
FROM CITY 
JOIN COUNTRY ON CITY.COUNTRYCODE = COUNTRY.CODE
WHERE CITY.POPULATION > 2000000;

SELECT NAME FROM CITY WHERE COUNTRYCODE = (SELECT CODE FROM COUNTRY WHERE NAME LIKE '%VAT%');

/*CUANTAS CIUDADES HAY EN LA ANTARTIDA*/
SELECT COUNT(*) FROM CITY WHERE COUNTRYCODE IN (SELECT CODE FROM COUNTRY WHERE NAME LIKE 'ANTARTIDA');

/*POBLACION TOTAL DE CADA CONTINENTE*/
SELECT CONTINENT, sum(POPULATION) AS POPULATION FROM COUNTRY GROUP BY CONTINENT;



